version: '3.4'
services:
  bpro:
    build:
      context: .devcontainer
      dockerfile: centos7-bld.dockerfile
      network: host
      args:
        USERNAME: ${USER}
        USERID: ${USERID}
        GROUPID: ${GROUPID}
        TZ: ${TZ}
        WEBPRO: ${WEBPRO}
        INTERNPRO: ${INTERNPRO}
        PLUGINSDK: ${PLUGINSDK}
        CRTOOL: ${CRTOOL}
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY_ENV}
      - XAUTHORITY=${XAUTH_ENV}
    hostname: ${HNAME}
    network_mode: host
    user: ${USER}
    volumes:
      - .:/bpvol/${COMPOSE_PROJECT_NAME}
      - ..:/bpvol/workspace
      - ~/.ssh:/home/${USER}/.ssh
      - ~/.gitconfig:/home/${USER}/.gitconfig
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
