version: '3.4'
services:
  bpro:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      network: host
      args:
        USERNAME: ${USER}
        USERID: ${USERID}
        GROUPID: ${GROUPID}
        WEBPRO: ${WEBPRO}
        INTERNPRO: ${INTERNPRO}
        PLUGINSDK: ${PLUGINSDK}
        CRTOOL: ${CRTOOL}
        CRWRAP: ${CRWRAP}
    hostname: ${HNAME}
    networks:
      - bpnet
    volumes:
      - .:/bpvol
    stdin_open: true
    tty: true
networks:
  bpnet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "9000"
# docker-compose build
# docker-compose run --rm bpro
